### ISSUE TITLE
Метод containsGame в классе GameStore не находит единственную или последнюю добавленную в каталог игру

### ISSUE THREAD

**Issue by LevchenkoTS** [LevchenkoTS/team-project#1]
# Описание
Метод проверки наличия игры в каталоге (сontainsGame) не находит игру, если добавлен только один объект и последнюю добавленную игру, если добавлено несколько объектов игры.
# Локация дефекта
https://github.com/LevchenkoTS/team-project/blob/44c7027f075e5244fa627241dbd962dda363871d/src/main/java/ru/netology/GameStore.java#L32-L39
# Шаги воспроизведения
1. Открыть код программы https://github.com/LevchenkoTS/team-project/blob/main/src/test/java/ru/netology/GameStoreTest.java в IDEA
2. Запустить тесты shouldContainLostGame и shouldAddGame
3. Посмотреть результаты тестов в консоли
*Ожидаемый результат: игра найдена в каталоге, результат true*
*Фактический результат: игра не найдена в каталоге, результат false*
# Скриншот
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/113931917/206567071-b4c917d6-e3c5-4977-b6bb-4354762890e8.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/113931917/206569920-98ddf49b-8efe-4b8c-8ed9-01a5c38291e7.png">

# Окружение
* **Операционная система:** macOS Monterey 12.6.1
* **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
*  **Java:** OpenJDK 11.0.16.1

**Comment by MikkiPolo** [comment]
## Исправлено
Дописан метод containsGame
Тесты проходят

<img width="1361" alt="Снимок экрана 2022-12-13 в 22 28 22" src="https://user-images.githubusercontent.com/113927421/207402964-93a6788e-b091-468a-a978-782a116a3ac6.png">
<img width="1361" alt="Снимок экрана 2022-12-13 в 22 28 13" src="https://user-images.githubusercontent.com/113927421/207403038-a0da8ebf-66c5-4add-a67c-ee3c492f6f41.png">
