### ISSUE TITLE
Метод addPlayTime в классе GameStore не суммирует время новой игры одного игрока с его прошлым значением

### ISSUE THREAD

**Issue by LevchenkoTS** [LevchenkoTS/team-project#2]
# Описание
Метод регистрации количества времени, которое игрок провел в игре (addPlayTime) не суммирует время, проведенное в новой игре с прошлым значением.
# Локация дефекта
https://github.com/LevchenkoTS/team-project/blob/44c7027f075e5244fa627241dbd962dda363871d/src/main/java/ru/netology/GameStore.java#L46-L51
# Шаги воспроизведения
1. Открыть код программы https://github.com/LevchenkoTS/team-project/blob/main/src/test/java/ru/netology/GameStoreTest.java в IDEA
2. Запустить тест sumOnePlayerTime
3. Посмотреть результат теста в консоли
*Ожидаемый результат: время новой игры игрока "Игрок1" суммируется с прошлым значением и равно 8, "Игрок1" провел в игре больше времени, чем "Игрок2" (4 часа)
*Фактический результат: отображается время только первой игры игрока "Игрок1" (2 часа) и не суммируется с последующими играми, "Игрок2" провел в игре больше времени
# Скриншот
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/113931917/207128972-ffe652bf-de7e-4f48-9aa0-f9b3167a3717.png">
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/113931917/207129183-86c84cbf-848d-4fd7-8bc2-39c2c2d6756e.png">

# Окружение
* **Операционная система:** macOS Monterey 12.6.1
* **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
*  **Java:** OpenJDK 11.0.16.1

**Comment by MikkiPolo** [comment]
# Исправлено
Дописан метод addPlayTime в классе GameStore
Тест проходит
<img width="1361" alt="Снимок экрана 2022-12-13 в 22 24 07" src="https://user-images.githubusercontent.com/113927421/207402201-b0e902b0-3fbc-480e-ad22-3222222d2967.png">
