### ISSUE TITLE
Метод play в классе Player не запоминает проигранное время игроком в игру

### ISSUE THREAD

**Issue by MikkiPolo** [LevchenkoTS/team-project#3]
# Описание
При добавлении нового игрока и установки игры, не происходит обновление мапа игрока с добавлением проигранного кол-ва времени в установленную игру 

# Локация дефекта
https://github.com/LevchenkoTS/team-project/blob/44c7027f075e5244fa627241dbd962dda363871d/src/main/java/ru/netology/Player.java#L33-L41

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/netology-code/javaqa-team-diplom/blob/main/src/main/java/ru/netology/Player.java#L33) в IDEA
2. Запустить [тест shouldSumGenreIfOneGame](https://github.com/netology-code/javaqa-team-diplom/blob/main/src/test/java/ru/netology/PlayerTest.java) в IDEA
3. Посмотреть на вывод консоли

*Ожидаемы результат: * Вывод результата 3 - кол-во проигранных часов
*Фактические результат: *Вывод результата 0 -кол-во проигранных часов

#Скриншот
<img width="1512" alt="Снимок экрана 2022-12-11 в 13 02 26" src="https://user-images.githubusercontent.com/113927421/206892970-e9487e1f-88b6-4b02-a9f2-d72e64721034.png">

# Окружение
* **Операционаая система:** macOS Ventura 13.0.1
* **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by LevchenkoTS** [comment]
Ошибка исправлена, тест проходит
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/113931917/207401599-d5160892-d708-4ef3-b6a4-a1a2741f8971.png">
