### ISSUE TITLE
Метод sumGenre в классе Player не суммирует количество проигранных игроком часов в игры в одном жанре

### ISSUE THREAD

**Issue by MikkiPolo** [LevchenkoTS/team-project#4]
# Описание
При установке игроком нескольких игр одного жанра, количество проигранных число должно суммироваться

# Локация дефекта
https://github.com/LevchenkoTS/team-project/blob/f3c8c1c25233c7bd08642ec68c84e892c5802ae9/src/main/java/ru/netology/Player.java#L50-L60

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/LevchenkoTS/team-project/blob/player/src/main/java/ru/netology/Player.java#L50-L60) в IDEA
2.  Запустить [тест shouldSumGenreIfTwoGame](https://github.com/LevchenkoTS/team-project/blob/player/src/test/java/ru/netology/PlayerTest.java)
3. Посмотреть на вывод консоли

*Ожидаемы результат:* Вывод результата 6 - кол-во проигранных часов в две игры одного жанра
*Фактический результат:* Вывод результата 0 - кол-во проигранных часов в две игры одного жанра

# Скриншот
<img width="1228" alt="Снимок экрана 2022-12-12 в 21 40 54" src="https://user-images.githubusercontent.com/113927421/207106410-129316d6-4f8f-42e9-bdb3-2801bb3d7206.png">

# Окружение
* **Операционаая система:** macOS Ventura 13.0.1
* **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by LevchenkoTS** [comment]
Ошибка исправлена, тест проходит 
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/113931917/207402280-54846ec8-d617-471e-8cd3-fda51fc4c78d.png">
