### ISSUE TITLE
Метод getMostPlayer в классе GameStore не выводит игрока, который проиграл в игру больше времени, если время равно 1

### ISSUE THREAD

**Issue by LevchenkoTS** [LevchenkoTS/team-project#5]
# Описание
Метод поиска игрока с максимальным временем, проигранным в игре (getMostPlayer) выводит null, если время игрока с максимальным временев в игре равно 1.
# Локация дефекта
https://github.com/LevchenkoTS/team-project/blob/44c7027f075e5244fa627241dbd962dda363871d/src/main/java/ru/netology/GameStore.java#L58-L69
# Шаги воспроизведения
1. Открыть код программы https://github.com/LevchenkoTS/team-project/blob/main/src/test/java/ru/netology/GameStoreTest.java в IDEA
2. Запустить тест mostPlayerTimeWhenOnePlayerPlayedOneOur
3. Посмотреть результат теста в консоли
*Ожидаемый результат: отображается "Игрок1", который проиграл в игру большее количество времени
*Фактический результат: отображается null
# Скриншот
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/113931917/207120562-f3cd1d8e-e1cf-4957-a069-eb8463d40e4a.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/113931917/207120912-2d65c71e-1442-47c9-9958-f057b8d0a76e.png">

# Окружение
* **Операционная система:** macOS Monterey 12.6.1
* **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
*  **Java:** OpenJDK 11.0.16.1

**Comment by MikkiPolo** [comment]
## Метод getMostPlayer в классе GameStore доработан
Считаю, что по условиям задачи, сравниваются люди которые играли, хотя бы час, и их должно быть несколько.
Т.к. в тесте играл всего лишь один игрок, то сравнивать не с кем, и метод возвращает null.
При добавлении в подготовку теста время игры для второго игрока, метод работает.
<img width="1361" alt="Снимок экрана 2022-12-13 в 22 37 42" src="https://user-images.githubusercontent.com/113927421/207405846-539e2f28-6394-40c2-aaa8-554c54f1117b.png">
<img width="1361" alt="Снимок экрана 2022-12-13 в 22 38 05" src="https://user-images.githubusercontent.com/113927421/207405905-2b264e88-56e2-4894-b142-61540acae367.png">

**Comment by LevchenkoTS** [comment]
Поскольку  в условии указано, что возвращается null только если игроков нет, могу предположить, что если в игру поиграл хотя бы один игрок, он должен высвечиваться в рейтинге лучшим и единственным. Предлагаю исправить метод, допустив возможность выставлять время в 1 час.

**Comment by MikkiPolo** [comment]
## Исправлено
исправлен код метода, тест проходит
<img width="1361" alt="Снимок экрана 2022-12-14 в 23 31 13" src="https://user-images.githubusercontent.com/113927421/207680252-83dd2c9b-8226-48fa-ac42-7a9473aae374.png">
