### ISSUE TITLE
Метод getMostPlayer в классе GameStore не выводит нескольких игроков, если у них одинаковое лучшее время игры 

### ISSUE THREAD

**Issue by LevchenkoTS** [LevchenkoTS/team-project#6]
# Описание
Метод поиска игрока с максимальным временем, проигранным в игре (getMostPlayer) не выводит нескольких игроков, если у них одинаковое лучшее время игры
# Локация дефекта
https://github.com/LevchenkoTS/team-project/blob/44c7027f075e5244fa627241dbd962dda363871d/src/main/java/ru/netology/GameStore.java#L58-L69
# Шаги воспроизведения
1. Открыть код программы https://github.com/LevchenkoTS/team-project/blob/main/src/test/java/ru/netology/GameStoreTest.java в IDEA
2. Запустить тест mostPlayerTimeWhenMoreOnePlayerBest
3. Посмотреть результат теста в консоли
*Ожидаемый результат: отображаются "Игрок2" и "Игрок3", у которых самое большое время в игре и оно равно
*Фактический результат: результатом может быть только 1 значение - 1 игрок
# Скриншот
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/113931917/207125621-e22278cd-0d56-44ec-8adb-3340846294a1.png">

# Окружение
* **Операционная система:** macOS Monterey 12.6.1
* **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
*  **Java:** OpenJDK 11.0.16.1

**Comment by MikkiPolo** [comment]
## Заданные условия теста не подлежат тестированию.
В условиях указано, что лучший игрок должен быть только один, в случае когда игроков с одинаковыми результатами несколько, игроки находятся в равных условиях, и не возможно выделить из них лучшего.
Метод getMostPlayer доработан и протестирован тестом mostPlayerTime
<img width="1361" alt="Снимок экрана 2022-12-13 в 22 54 58" src="https://user-images.githubusercontent.com/113927421/207408698-1d810bbf-d415-4f56-8261-a4663edc2c5f.png">
