### ISSUE TITLE
Метод getSumPlayedTime в классе GameStore не суммирует общее время всех игроков

### ISSUE THREAD

**Issue by LevchenkoTS** [LevchenkoTS/team-project#7]
# Описание
Метод, который суммирует время всех игроков, проведенного в игре (getSumPlayedTime) всегда выводит 0
# Локация дефекта
https://github.com/LevchenkoTS/team-project/blob/44c7027f075e5244fa627241dbd962dda363871d/src/main/java/ru/netology/GameStore.java#L75-L77
# Шаги воспроизведения
1. Открыть код программы https://github.com/LevchenkoTS/team-project/blob/main/src/test/java/ru/netology/GameStoreTest.java в IDEA
2. Запустить тест sumPlayersTime
3. Посмотреть результат теста в консоли
*Ожидаемый результат:  выводится время, проведенное в игре всеми игроками 
*Фактический результат: выводится 0
# Скриншот
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/113931917/207400327-36a4eb33-d54e-47f3-9473-03b0ed29445a.png">

# Окружение
* **Операционная система:** macOS Monterey 12.6.1
* **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
*  **Java:** OpenJDK 11.0.16.1

**Comment by MikkiPolo** [comment]
## Исправлено
Метод getSumPlayedTime доработан
Тест проходит
<img width="1361" alt="Снимок экрана 2022-12-13 в 22 43 11" src="https://user-images.githubusercontent.com/113927421/207406410-dbcce1f5-5278-4cd5-a4ca-976daafd71bc.png">
