### ISSUE TITLE
Метод mostPlayerByGenre в классе Player не выводит самую проигрываемую игру по жанру

### ISSUE THREAD

**Issue by MikkiPolo** [LevchenkoTS/team-project#8]
# Описание
Данный метод должен выводить самую проигрываемую игру принимая за поисковое значение жанр игры.

# Локация дефекта
https://github.com/LevchenkoTS/team-project/blob/b6337e9db6d13e073b9dff07d7c9f3d417b7dbdb/src/main/java/ru/netology/Player.java#L64-L67

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/LevchenkoTS/team-project/blob/player/src/main/java/ru/netology/Player.java#L64-L67)
2. Запустить тест [mostPlayerByGenre](https://github.com/LevchenkoTS/team-project/blob/player/src/test/java/ru/netology/PlayerTest.java)
3. Посмотреть результат теста в консоли

*Ожидаемый результат:* Вывод результата самой проигрываемой игры Game2
*Фактический результат:* Вывод результат самой проигрываемой игры *null*

# Скриншот
<img width="1246" alt="Снимок экрана 2022-12-12 в 23 52 34" src="https://user-images.githubusercontent.com/113927421/207129990-31989c88-5ab9-4606-b623-edab8ca5c5cb.png">

# Окружение
* **Операционаая система:** macOS Ventura 13.0.1
* **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by LevchenkoTS** [comment]
Ошибка исправлена, в тесте Game actual изменен на String, тест проходит 
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/113931917/207406155-f6066e1b-6af8-44bb-8113-2b989d245d74.png">
